### ISSUE TITLE
Support CJS and ESM

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-api-clients#17]
### Description/Context
We should support both CommonJS (aka CJS; old, node-style import/export) and the more modern ES Modules (aka ESM) syntax. Providing both module types is very common for libraries.

ES Modules tend to be better tree-shakeable and result in smaller bundles. (See [this comment](https://github.com/mitodl/open-api-clients/pull/5#discussion_r1469821022) on #5). So we should definitely support ESM.

But some tooling only supports CJS. In particular, Jest does not support ESM and, by default, does not transform ESM import/exports in `node_modules`. In order to a module Jest "just work" with Jest, it needs a CJS version.

### Plan/Design
Provide both CJS and ESM exports so that the javascript runtime can pick whichever one it wants. This can be done as described here: https://nodejs.org/api/packages.html#approach-2-isolate-state ; **Many** packages do this in the wild, but two quick examples:
- https://github.com/TanStack/query/blob/main/packages/react-query/package.json
- https://github.com/axios/axios/blob/v1.x/package.json

**Comment by rhysyngsun** [comment]
@ChristopherChudzicki I think we can close this?

**Comment by ChristopherChudzicki** [comment]
Agree.
